### ISSUE TITLE
Select Icon, Edit Label does not accept numeric digits

### ISSUE THREAD

**Issue by ajstadlin** [abstractspoon/ToDoList_8.0#2]
This is probably a `PreTranslateMessage` issue in *ToDoList_8.0\Core\ToDoList\TDLTaskIconDlg.cpp*  

Steps to repeat.

1. Open a ToDoList and include an *Icon* column.
2. Click on the icon. This will launch the *Select Task Icon* dialog
3. Click on any icon. For testing, I click on the *bug* icon, with label "41"
4. Click the *Edit Label* button and try to change the label to "141"

The result is the Icon with label "1" is selected and the edit mode loses focus, cancelling the edit.

This problem occurs in ToDoList 8.0.B7 (Beta Release) and ToDoList 7.2.23.0 (Stable Release)

This works correctly in ToDoList 7.1.3.2 (Stable Release)

**Comment by abstractspoon** [comment]
Hi
Could you possibly repost this to our [public forum](https://www.abstractspoon.com/phpBB/viewforum.php?f=10) please?

**Comment by ajstadlin** [comment]
I tried to register in the forum and report it there first, but for some reason I do not get an Activation email.  I tried to resend the Activation email several times.
